Baotro/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Baotro import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('auth/', include('authentication.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path('post-list/', views.post_list, name='post-list'),
    path('image-list/', views.image_list, name='image-list'),
    path('video-list/', views.video_list, name='video-list'),
    path('file-list/', views.file_list, name='file-list'),
    path('post-edit/', views.post_edit, name='post-edit'),
    path('post-new/', views.post_new, name='post-new'),
    path('post-detail/', views.post_detail, name='post-detail'),
    path('image-detail/', views.image_detail, name='image-detail'),
    path('image-new/', views.image_new, name='image-new'),
]

blog/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth import get_user_model
from django.db import models
import os

# Create your models here.
from django.utils import timezone


class Post(models.Model):
    type_choices = [
        ('0', 'Tin trung tâm'),
        ('1', 'Tin trong tỉnh'),
        ('2', 'Hoàn cảnh cần giúp đỡ'),
        ('3', 'Thông tin chỉ đạo, điều hành'),
    ]
    author = models.ForeignKey(get_user_model(),blank=False, on_delete=models.CASCADE)
    title = models.CharField("Tiêu đề",max_length=200,blank=False)
    image = models.ImageField("Hình ảnh minh họa",blank=False)
    # video_link = models.URLField(max_length=2000, blank=True)
    description = models.CharField("Mô tả",max_length=500, blank=False)
    content = RichTextField("Nội dung",blank=False)
    type = models.CharField("Loại bài đăng",default='0', max_length=100, choices=type_choices)
    created_date = models.DateTimeField("Ngày khởi tạo",default=timezone.now)

    # published_date = models.DateTimeField(blank=True, null=True)
    #
    # def publish(self):
    #     self.published_date = timezone.now()
    #     self.save()

    def __str__(self):
        return self.title


class PostVideo(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    video_link = models.URLField(max_length=2000)
    description = models.CharField(max_length=500, blank=True)
    created_date = models.DateTimeField(default=timezone.now)

    # published_date = models.DateTimeField(blank=True, null=True)
    #
    # def publish(self):
    #     self.published_date = timezone.now()
    #     self.save()

    def __str__(self):
        return self.title


class PostImage(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    # image = models.ImageField()
    description = models.CharField(max_length=500, blank=True)
    created_date = models.DateTimeField(default=timezone.now)

    # published_date = models.DateTimeField(blank=True, null=True)
    #
    # def publish(self):
    #     self.published_date = timezone.now()
    #     self.save()

    def default_image(self):
        return Image.objects.filter(post_image=self).first()

    def __str__(self):
        return self.title


class Image(models.Model):
    post_image = models.ForeignKey(PostImage, on_delete=models.CASCADE)
    image = models.ImageField()


class PostFile(models.Model):
    type_choices = [
        ('0', 'Cải cách hành chính'),
        ('1', 'Thông báo')
    ]
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    number = models.CharField(max_length=200, default='')
    name = models.CharField(max_length=200, default='')
    file = models.FileField()
    type = models.CharField("Loại văn bản", default='0', max_length=100, choices=type_choices)
    created_date = models.DateTimeField(default=timezone.now)

    # published_date = models.DateTimeField(blank=True, null=True)
    #
    # def publish(self):
    #     self.published_date = timezone.now()
    #     self.save()

    def filename(self):
        return os.path.basename(self.file.name)

    def extension(self):
        name, extension = os.path.splitext(self.file.name)
        return extension

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from authentication.models import UserProfile
from blog.models import Post, PostImage, Image


class ImageForm(forms.Form):
    images = forms.FileField(widget=forms.ClearableFileInput(attrs={'class': 'custom-file-input', 'multiple': True}))


class PostImageForm(forms.ModelForm):
    class Meta:
        model = PostImage
        fields = ('title', 'description')
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Nhập tên bài đăng'
                }
            ),
            'description': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Nhập mô tả bài viết'
                }
            ),
        }


class PostNewForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'image', 'description', 'content')
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Nhập tên bài đăng'
                }
            ),
            'image': forms.FileInput(
                attrs={
                    'class': 'custom-file-input'
                }
            ),
            # 'video_link': forms.TextInput(
            #     attrs={
            #         'class': 'form-control',
            #         'placeholder': 'Nhập đường dẫn liên kết video'
            #     }
            # ),
            'description': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Nhập mô tả bài viết'
                }
            )
        }


class ExtendedUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=150)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)

        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('location', 'birthday', 'gender', 'phone_number')

blog/views.py
from django.contrib.auth.models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect

# Create your views here.
from authentication.models import UserProfile
from blog.forms import PostNewForm, ImageForm, PostImageForm
from blog.models import Post, PostImage, PostVideo, PostFile, Image


def post_list(request):
    type = request.GET.get('type')
    if type:
        posts_page =Post.objects.filter(type=type).order_by('-created_date')
    else:
        posts_page = Post.objects.all().order_by('-created_date')
    page = request.GET.get('page', 1)
    paginator = Paginator(posts_page, 5)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    files = PostFile.objects.all().order_by('-created_date')[:5]
    images = PostImage.objects.all().order_by('-created_date')[:8]
    return render(request, 'blog/post-list.html', {'posts': posts, 'files': files, 'images': images})


def post_edit(request):
    return render(request, 'blog/post-edit.html')


def post_new(request):
    if request.method == 'POST':
        form = PostNewForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:post-list')
    else:
        form = PostNewForm()
    files = PostFile.objects.all().order_by('-created_date')[:5]
    images = PostImage.objects.all().order_by('-created_date')[:8]
    return render(request, 'blog/post-new.html', {'form': form, 'files': files, 'images': images})


def post_detail(request):
    post_id = request.GET.get('id', 1)
    post = Post.objects.get(id=post_id)
    files = PostFile.objects.all().order_by('-created_date')[:5]
    images = PostImage.objects.all().order_by('-created_date')[:8]
    return render(request, 'blog/post-detail.html', {'post': post, 'files': files, 'images': images})


def image_detail(request):
    post_id = request.GET.get('id', 1)
    post = PostImage.objects.get(id=post_id)
    images_detail = Image.objects.filter(post_image_id=post_id)
    files = PostFile.objects.all().order_by('-created_date')[:5]
    images = PostImage.objects.all().order_by('-created_date')[:8]
    return render(request, 'blog/image-detail.html', {'post': post, 'images_detail': images_detail, 'files': files, 'images': images})


def image_list(request):
    posts_page = PostImage.objects.all().order_by('-created_date')
    page = request.GET.get('page', 1)
    paginator = Paginator(posts_page, 3)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    files = PostFile.objects.all().order_by('-created_date')[:5]
    images = PostImage.objects.all().order_by('-created_date')[:8]
    return render(request, 'blog/image-list.html', {'posts': posts, 'files': files, 'images': images})


def video_list(request):
    posts_page = PostVideo.objects.all().order_by('-created_date')
    page = request.GET.get('page', 1)
    paginator = Paginator(posts_page, 3)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    files = PostFile.objects.all().order_by('-created_date')[:5]
    images = PostImage.objects.all().order_by('-created_date')[:8]
    return render(request, 'blog/video-list.html', {'posts': posts, 'files': files, 'images': images})


def file_list(request):
    type = request.GET.get('type')
    if type:
        posts = PostFile.objects.filter(type=type).order_by('-created_date')
    else:
        posts = PostFile.objects.all().order_by('-created_date')
    files = PostFile.objects.all().order_by('-created_date')[:5]
    images = PostImage.objects.all().order_by('-created_date')[:8]
    return render(request, 'blog/file-list.html', {'posts': posts, 'files': files, 'images': images})


def image_new(request):
    if request.method == 'POST':
        post_image_form = PostImageForm(request.POST, request.FILES)
        image_form = ImageForm(request.POST, request.FILES)
        files = request.FILES.getlist('images')
        if image_form.is_valid() and post_image_form.is_valid():
            post_image = post_image_form.save(commit=False)
            post_image.author = request.user
            post_image.save()
            for file in files:
                Image.objects.create(post_image=post_image, image=file)
            return redirect('blog:image-list')
    else:
        image_form = ImageForm()
        post_image_form = PostImageForm()
    files = PostFile.objects.all().order_by('-created_date')[:5]
    images = PostImage.objects.all().order_by('-created_date')[:8]
    return render(request, 'blog/image-new.html', {'image_form': image_form, 'post_image_form': post_image_form, 'files': files, 'images': images})

templates/blog/file-list.html
{% extends 'base.html' %}
{% load static %}
{% block name %}Danh sách file{% endblock %}
{% block title %}Danh sách file{% endblock %}
{% block url %}{% url 'blog:file-list' %}{% endblock %}
{% block base %}
    <table class="table table-bordered">
        <thead>
        <tr class="d-flex">
            <th class="col-1">#</th>
            <th class="col-2">Số hiệu</th>
            <th class="col-7">Tên văn bản</th>
            <th class="col-2">Ngày ban hành</th>
        </tr>
        </thead>
        <tbody>
        {% for post in posts %}
            <tr class="d-flex">
                <th class="col-1" scope="row">{{ forloop.counter }}</th>
                <td class="col-2">{{ post.number }}</td>
                <td class="col-7"><a href="{{ post.file.url }}">{{ post.name }}</a></td>
                <td class="col-2">{{ post.created_date|date:"d/m/Y" }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/blog/image-detail.html
{% extends 'base.html' %}
{% load static %}
{% block name %}Hình ảnh{% endblock %}
{% block title %}{{ post.title }}{% endblock %}
{% block base %}
    <div class="post-title">{{ post.title }}</div>
    <div class="description">{{ post.description }}</div>
    <div class="clearfix"><div class="date">{{ post.created_date|date:"d/m/Y" }}</div></div>
    {% for image_detail in images_detail %}
        <div class="post-image"><img src="{{ image_detail.image.url }}"></div>
    {% endfor %}
{% endblock %}

templates/blog/image-list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Danh sách hình ảnh{% endblock %}
{% block name %}Danh sách hình ảnh{% endblock %}
{% block base %}
    <div class="content-wrapper">
        {% for post in posts %}
            <div class="post-item">
                <a href="{% url 'blog:image-detail' %}?id={{ post.id }}">
                    <div class="title">{{ post.title }}</div>
                    <div class="image"><img src="{{ post.default_image.image.url }}"></div>
                    <div class="description">{{ post.description }}</div>
                    <div class="clearfix"><div class="date">{{ post.created_date|date:"d/m/Y" }}</div></div>
                </a>
            </div>
        {% endfor %}
    </div>
    {% include "blog/pagination.html" %}
{% endblock %}

templates/blog/image-new.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Thêm hình ảnh{% endblock %}
{% block name %}Thêm hình ảnh{% endblock %}
{% block base %}
    <div class="content-wrapper">
        <form method="post" action="{% url 'blog:image-new' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="id_image">Hình ảnh:</label>
            <div class="custom-file">
                {{ image_form.images }}
                <label class="custom-file-label" for="id_image">Chọn hình ảnh</label>
            </div>
            <label for="id_title">Tên bài đăng:</label>
            {{ post_image_form.title }}
            <label for="id_description">Mô tả:</label>
            {{ post_image_form.description }}
            <input style="float: right; margin-top: 30px; margin-bottom: 30px" class="btn btn-success" type="submit"
                   value="Tạo bài viết">
        </form>
    </div>
{% endblock %}

templates/blog/pagination.html
<div class="pagination-bottom">
    <div class="container">
        {% if posts.has_other_pages %}
            <ul class="pagination">
                {% if posts.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ posts.previous_page_number }}">&laquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">&laquo;</span>
                    </li>
                {% endif %}
                {% for i in posts.paginator.page_range %}
                    {% if posts.number == i %}
                        <li class="page-item active">
                            <span class="page-link">{{ i }} <span class="sr-only">(current)</span></span>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
                {% if posts.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ posts.next_page_number }}">&raquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">&raquo;</span>
                    </li>
                {% endif %}
            </ul>
        {% endif %}
    </div>
</div>

templates/blog/post-detail.html
{% extends 'base.html' %}
{% load static %}
{% block name %}Bài đăng{% endblock %}
{% block title %}{{ post.title }}{% endblock %}
{#{% block url %}{% url 'blog:post-list' %}{% endblock %}#}
{% block base %}
    <div class="post-title">{{ post.title }}</div>
    <div class="post-image"><img src="{{ post.image.url }}" alt="{{ post.title }}"></div>
    {% if post.video_link %}
        <div class="post-video">
            <iframe width="100%" height="315"
                    src="{{ post.video_link }}">
            </iframe>
        </div>
    {% endif %}
    <div class="post-content">{{ post.content | safe }}</div>
{% endblock %}

templates/blog/post-edit.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Chỉnh sửa bài đăng{% endblock %}
{% block base %}

{% endblock %}

templates/blog/post-list.html
{% extends 'base.html' %}
{% load static %}
{% block name %}Danh sách bài đăng{% endblock %}
{% block title %}Danh sách bài đăng{% endblock %}
{% block url %}{% url 'blog:post-list' %}{% endblock %}
{% block base %}
    <div class="content-wrapper">
        {% for post in posts %}
            <div class="post-item">
                <a href="{% url 'blog:post-detail' %}?id={{ post.id }}">
                    <div class="title">{{ post.title }}</div>
                    <div class="image"><img src="{{ post.image.url }}"></div>
                    <div class="clearfix"><div class="date">{{ post.created_date }}</div></div>
                </a>
            </div>
        {% endfor %}
    </div>
    {% include "blog/pagination.html" %}
    {#    <div class="pagination-bottom">#}
    {#        <div class="container">#}
    {#            {% if posts.has_other_pages %}#}
    {#                <ul class="pagination">#}
    {#                    {% if posts.has_previous %}#}
    {#                        <li class="page-item">#}
    {#                            <a class="page-link" href="?page=1">#}
    {#                                <i class="fa fa-angle-double-left" aria-hidden="true"></i>#}
    {#                            </a>#}
    {#                        </li>#}
    {#                        <li class="page-item">#}
    {#                            <a class="page-link" href="?page={{ posts.previous_page_number }}"><i#}
    {#                                    class="fa fa-angle-left" aria-hidden="true"></i></a>#}
    {#                        </li>#}
    {#                    {% else %}#}
    {#                        <li class="page-item disabled">#}
    {#                            <span class="page-link"><i class="fa fa-angle-double-left" aria-hidden="true"></i></span>#}
    {#                        </li>#}
    {#                        <li class="page-item disabled">#}
    {#                            <span class="page-link"><i class="fa fa-angle-left" aria-hidden="true"></i></span>#}
    {#                        </li>#}
    {#                    {% endif %}#}
    {#                    {% for num in posts.paginator.page_range %}#}
    {#                        {% if posts.number == num %}#}
    {#                            <li class="page-item active">#}
    {#                                <span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>#}
    {#                            </li>#}
    {#                        {% elif num > posts.number|add:'-3' and num < posts.number|add:'3' %}#}
    {#                            <li class="page-item">#}
    {#                                <a class="page-link" href="?page={{ num }}">{{ num }}</a>#}
    {#                            </li>#}
    {#                        {% endif %}#}
    {#                    {% endfor %}#}
    {#                    {% if posts.has_next %}#}
    {#                        <li class="page-item">#}
    {#                            <a class="page-link" href="?page={{ posts.next_page_number }}">#}
    {#                                <i class="fa fa-angle-right" aria-hidden="true"></i>#}
    {#                            </a>#}
    {#                        </li>#}
    {#                        <li class="page-item">#}
    {#                            <a class="page-link" href="?page={{ posts.paginator.num_pages }}">#}
    {#                                <i class="fa fa-angle-double-right" aria-hidden="true"></i>#}
    {#                            </a>#}
    {#                        </li>#}
    {#                    {% else %}#}
    {#                        <li class="page-item disabled">#}
    {#                            <span class="page-link">#}
    {#                                <i class="fa fa-angle-right" aria-hidden="true"></i>#}
    {#                            </span>#}
    {#                        </li>#}
    {#                        <li class="page-item disabled">#}
    {#                            <span class="page-link">#}
    {#                                <i class="fa fa-angle-double-right" aria-hidden="true"></i>#}
    {#                            </span>#}
    {#                        </li>#}
    {#                    {% endif %}#}
    {#                </ul>#}
    {#            {% endif %}#}
    {#        </div>#}
    {#    </div>#}
{% endblock %}

templates/blog/post-new.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Tạo bài đăng{% endblock %}
{% block name %}Tạo bài đăng{% endblock %}
{% block base %}
    <div class="content-wrapper">
        <form method="post" action="{% url 'blog:post-new' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="id_title">Tên bài đăng:</label>
            {{ form.title }}
            <label for="id_image">Hình ảnh minh họa:</label>
            <div class="custom-file">
                {{ form.image }}
                <label class="custom-file-label" for="id_image">Chọn hình ảnh</label>
            </div>
{#            <label for="id_video_link">Đường dẫn video:</label>#}
{#            {{ form.video_link }}#}
            <label for="id_description">Mô tả:</label>
            {{ form.description }}
            <label for="cke_id_content">Nội dung chi tiết:</label>
            <div class="d-flex justify-content-center">
                {{ form.content | safe }}
                {{ form.media }}
            </div>
            <input style="float: right; margin-top: 30px; margin-bottom: 30px" class="btn btn-success" type="submit" value="Tạo bài viết">
        </form>
    </div>
{% endblock %}

templates/blog/video-list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Danh sách video{% endblock %}
{% block name %}Danh sách video{% endblock %}
{% block base %}
    <div class="content-wrapper">
        {% for post in posts %}
            <div class="post-item">
                <div class="title">{{ post.title }}</div>
                {{post.video_link }}
                <div class="post-video">
                    <iframe src="{{ post.video_link }}" frameborder="0"
                            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                            allowfullscreen></iframe>
                </div>
                <div class="description">{{ post.description }}</div>
                <div class="clearfix"><div class="date">{{ post.created_date|date:"d/m/Y" }}</div></div>
            </div>
        {% endfor %}
    </div>
    <div class="pagination-bottom">
        <div class="container">
            {% if posts.has_other_pages %}
                <ul class="pagination">
                    {% if posts.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ posts.previous_page_number }}">&laquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <span class="page-link">&laquo;</span>
                        </li>
                    {% endif %}
                    {% for i in posts.paginator.page_range %}
                        {% if posts.number == i %}
                            <li class="page-item active">
                                <span class="page-link">{{ i }} <span class="sr-only">(current)</span></span>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if posts.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ posts.next_page_number }}">&raquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <span class="page-link">&raquo;</span>
                        </li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
    </div>
{% endblock %}