Baotro/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Baotro import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('auth/', include('authentication.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path('post-list/', views.post_list, name='post-list'),
    path('image-list/', views.image_list, name='image-list'),
    path('video-list/', views.video_list, name='video-list'),
    path('file-list/', views.file_list, name='file-list'),
    path('post-edit/', views.post_edit, name='post-edit'),
    path('post-new/', views.post_new, name='post-new'),
    path('post-detail/', views.post_detail, name='post-detail'),
    path('image-detail/', views.image_detail, name='image-detail'),
    path('image-new/', views.image_new, name='image-new'),
]

home/urls.py
from django.urls import path

from home import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('org-chart', views.org_chart, name='org-chart'),
    path('content', views.content, name='content'),
]

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon/favicon.png' %}"/>
</head>
<body>
    <!-- Messenger Plugin chat Code -->
    <div id="fb-root"></div>
      <script>
        window.fbAsyncInit = function() {
          FB.init({
            xfbml            : true,
            version          : 'v10.0'
          });
        };

        (function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = 'https://connect.facebook.net/vi_VN/sdk/xfbml.customerchat.js';
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
      </script>

      <!-- Your Plugin chat code -->
      <div class="fb-customerchat"
        attribution="page_inbox"
        page_id="104963985059060">
      </div>
<div id="header">
    <img class="image-header" src="{% static 'images/header.jpg' %}">
    <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
        <div class="container"><a class="navbar-brand" href="{% url 'home:index' %}"><i
                class="icon-home fa fa-home"></i> Trang chủ</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09"
                    aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarsExample09">
                <ul class="navbar-nav m-auto">
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == "/about" %}active{% endif %}" href="{% url 'home:about' %}">Giới thiệu</a>
                            <div class="dropdown-menu dropdown-content" aria-labelledby="dropdown09">
                            <a class="dropdown-item" href="{% url 'home:about' %}">Giới thiệu</a>
                            <a class="dropdown-item" href="{% url 'home:org-chart' %}">Sơ đồ tổ chức</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == "/blog/post-list/" %}active{% endif %}" href="{% url 'blog:post-list' %}">Tin tức- Sự kiện</a>
                        <div class="dropdown-menu dropdown-content" aria-labelledby="dropdown09">
                            <a class="dropdown-item" href="{% url 'blog:post-list' %}?type=0">Tin trung tâm</a>
                            <a class="dropdown-item" href="{% url 'blog:post-list' %}?type=1">Tin trong tỉnh</a>
                            <a class="dropdown-item" href="{% url 'blog:post-list' %}?type=2">Hoàn cảnh cần giúp đỡ</a>
                            <a class="dropdown-item" href="{% url 'blog:post-list' %}?type=3">Thông tin chỉ đạo, điều hành</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == "/blog/file-list/" %}active{% endif %}" href="{% url 'blog:file-list' %}">Văn bản</a>
                        <div class="dropdown-menu dropdown-content" aria-labelledby="dropdown09">
                            <a class="dropdown-item" href="{% url 'blog:file-list' %}">Văn bản mới</a>
                            <a class="dropdown-item" href="{% url 'blog:file-list' %}?type=0">Cải cách hành chính</a>
                            <a class="dropdown-item" href="{% url 'blog:file-list' %}?type=1">Thông báo</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == "/blog/image-list/" %}active{% endif %}" href="{% url 'blog:image-list' %}">Thư viện ảnh</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == "/blog/video-list/" %}active{% endif %}" href="{% url 'blog:video-list' %}">Thư viện video</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Liên kết</a>
                        <div class="dropdown-menu dropdown-content" aria-labelledby="dropdown09">
                            <a class="dropdown-item" target="_blank" href="http://www.baria-vungtau.gov.vn/sphere/baria/vungtau/page/trang-chu.cpx">UBND tỉnh BR-VT</a>
                            <a class="dropdown-item" target="_blank" href="http://soldtbxh.baria-vungtau.gov.vn/">Sở lao động TB&XH</a>
                            <a class="dropdown-item" target="_blank" href="https://www.facebook.com/TTCongtacxahoiVaBaotrotreem">Fanpage</a>
                            <a class="dropdown-item" target="_blank" href="http://ttbaotrotreemvungtau.com/admin/login/?next=/admin/">Đăng nhập</a>
                        </div>
                    </li>
                </ul>
                <form class="form-inline my-2 my-md-0">
                    <input class="form-control" type="text" placeholder="Tìm kiếm" aria-label="Search">
                </form>
            </div>
        </div>
    </nav>
</div>
<div id="main">
    <div class="container main">
        <div class="row">
            <div class="col-md-8 left">
            <a href="{% block url %} {% endblock %}" class="arrow-title">{% block name %} {% endblock %}</a>
                {% block base %}
                {% endblock %}
            </div>
            <div class="col-md-4 right">
                <div class="item-right">
                    <a href="{% url 'blog:file-list' %}" class="arrow-title">Danh sách văn bản</a>
                    <ul class="files">
                        {% for file in files %}
                            <li class="file-item">
                                <div class="title clearfix">
                                    <a class="file-title" href="{{ file.file.url }}">{{ file.number }}</a>
                                    <div class="date">({{ file.created_date|date:"d/m/Y" }})</div>
                                </div>
                                <div class="name">{{ file.name }}</div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="item-right">
                    <a href="{% url 'blog:video-list' %}" class="arrow-title">Video hoạt động</a>
                    <iframe
                            src="https://www.youtube.com/embed/stjuHGFGP3E">
                    </iframe>
                </div>
                <div class="item-right">
                    <a href="#" class="arrow-title">Hỗ trợ từ trung tâm</a>
                    <div class="content" style="text-align: center">
{#                        <div style="font-size: 20px; font-weight: 500">Số điện thoại</div>#}
{#                        <div style="font-size: 20px; font-weight: 500; color: rgb(1, 100, 167);">0254 3560 522, 02543 615 339 </div>#}
                        <div style="font-size: 22px; font-weight: 600; color: red"><i class="fa fa-phone"></i> Hotline:</div>
                        <div style="font-size: 22px; font-weight: 600; color: red"> (0254)3 560 522</div>
                        <div style="font-size: 22px; font-weight: 600; color: red"> (0254)3 615 339</div>
                        <div style="font-size: 20px; font-weight: 500; color: rgb(1, 100, 167)"><i class="fa fa fa-envelope"></i> Email:</div>
                        <div style="font-size: 20px; color: rgb(1, 100, 167)">trungtamctxhvabtte@gmail.com</div>
                    </div>
                </div>
                <div class="item-right">
                    <a href="https://www.facebook.com/TTCongtacxahoiVaBaotrotreem" class="arrow-title">Fanpage facebook của trung
                        tâm</a>
                    <div class="fb-page" data-href="https://www.facebook.com/TTCongtacxahoiVaBaotrotreem" data-tabs="timeline"
                         data-width="500"
                         data-height="300" data-small-header="false" data-adapt-container-width="true"
                         data-hide-cover="false" data-show-facepile="true">
                        <blockquote cite="https://www.facebook.com/TTCongtacxahoiVaBaotrotreem" class="fb-xfbml-parse-ignore"><a
                                href="https://www.facebook.com/TTCongtacxahoiVaBaotrotreem">Facebook</a></blockquote>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="image-list container">
    <a href="{% url 'blog:image-list' %}" class="arrow-title">Danh sách hình ảnh</a>
    <div id="carousel-example" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner row w-100 mx-auto" role="listbox">
            {% for image in images %}
                <a href="{% url 'blog:image-detail' %}?id={{ image.id }}"
                   class="carousel-item col-12 col-sm-6 col-md-4 col-lg-3 {% if image == images.0 %} active {% endif %}">
                    <div class="full-image">
                        <img src="{{ image.default_image.image.url }}" class="img-fluid mx-auto d-block" alt="img1">
                    </div>
                    <h5 class="title">{{ image.title }}</h5>
                    <p class="description">{{ image.description }}</p>
                </a>
            {% endfor %}
        </div>
        <div>
            <a class="carousel-control-prev" href="#carousel-example" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel-example" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>
<div id="footer">
    <div class="container footer">
        <!--Google map-->
        <div id="gmap" class="contact-map">
            <iframe src="https://maps.google.com/maps?q=Trung tâm bảo trợ trẻ em vũng tàu&t=&z=13&ie=UTF8&iwloc=&output=embed"
                    frameborder="0"
                    style="apsborder:0" allowfullscreen></iframe>
        </div>
        <!--Google Maps-->
    </div>
    <div class="contact-title container">Liên hệ với chúng tôi</div>
    <div class="contact container">
        <div class="footer-name">TRUNG TÂM CÔNG TÁC XÃ HỘI VÀ BẢO TRỢ TRẺ EM TỈNH BÀ RỊA - VŨNG TÀU</div>
        <div class="footer-content">Địa chỉ: 26 đường Ngô Quyền, phường Thắng Nhất, Thành phố Vũng Tàu, tỉnh Bà Rịa - Vũng Tàu.
        </div>
        <div class="footer-content">Điện thoại: 0254 3560 522 - 02543 615 339 | Fax: 0254 3560 522</div>
        <div class="footer-content">Website: ttbaotrotreemvungtau.com | Email: trungtamctxhvabtte@gmail.com</div>
        <div class="social-contact">
            <div class="social-icons">
                <ul class="nav nav-pills">
                    <li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-twitter"></i></a></li>
                    <li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-linkedin"></i></a>
                    </li>
                    <li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-dribbble"></i></a>
                    </li>
                    <li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-google-plus"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="{% static 'js/main.js' %}"></script>
<div id="fb-root"></div>
<script async defer crossorigin="anonymous"
        src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v5.0&appId=423326028560878&autoLogAppEvents=1"></script>
</body>
</html>